In [4]:
import pandas as pd

# Carregamento da planilha
df = pd.read_excel("new_df_traduzido.xlsx")
df.head()

,País,Ano,Desenvolvimento,Expectativa_de_vida,Mortalidade_adulta,Mortes_infantis,Álcool,Porcentagem_despesas,Hepatite_B,Sarampo,...,Poliomielite,Despesa_total,Difteria,HIV/AIDS,PIB,População,Magreza_1_a_19_anos,Magreza_5_a_9_anos,Composição_de_renda,Escolaridade
0,Afghanistan,2014,Developing,59.9,271,64,0.01,73.523582,62,492,...,58,8.18,62,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
1,Afghanistan,2013,Developing,59.9,268,66,0.01,73.219243,64,430,...,62,8.13,64,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
2,Afghanistan,2012,Developing,59.5,272,69,0.01,78.184215,67,2787,...,67,8.52,67,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
3,Afghanistan,2011,Developing,59.2,275,71,0.01,7.097109,68,3013,...,68,7.87,68,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
4,Afghanistan,2010,Developing,58.8,279,74,0.01,79.679367,66,1989,...,66,9.20,66,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2

In [5]:
# Ver informações básicas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1290 entries, 0 to 1289
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   País                  1290 non-null   object
 1   Ano                   1290 non-null   int64
 2   Desenvolvimento       1290 non-null   object
 3   Expectativa_de_vida   1290 non-null   float64
 4   Mortalidade_adulta    1290 non-null   int64
 5   Mortes_infantis       1290 non-null   int64
 6   Álcool                1290 non-null   float64
 7   Porcentagem_despesas  1290 non-null   float64
 8   Hepatite_B            1290 non-null   int64
 9   Sarampo               1290 non-null   int64
 10  BMI                   1290 non-null   float64
 11  under-five_deaths     1290 non-null   int64
 12  Poliomielite          1290 non-null   int64
 13  Despesa_total         1290 non-null   float64
 14  Difteria              1290 non-null   int64
 15  HIV/AIDS              1290 non-null   float64
 16  PIB                   1290 non-null   float64
 17  População             1290 non-null   float64
 18  Magreza_1_a_19_anos   1290 non-null   float64
 19  Magreza_5_a_9_anos    1290 non-null   float64
 20  Composição_de_renda   1290 non-null   float64
 21  Escolaridade          1290 non-null   float64
dtypes: float64(12), int64(8), object(2)
memory usage: 221.8+ KB

In [6]:
# Estatísticas descritivas
df.describe()

,Ano,Expectativa_de_vida,Mortalidade_adulta,Mortes_infantis,Álcool,Porcentagem_despesas,Hepatite_B,Sarampo,BMI,under-five_deaths,Poliomielite,Despesa_total,Difteria,HIV/AIDS,PIB,População,Magreza_1_a_19_anos,Magreza_5_a_9_anos,Composição_de_renda,Escolaridade
count,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1.290000e+03,1290.000000,1290.000000,1290.000000,1290.000000
mean,2008.030233,70.263488,156.814729,14.870543,4.621535,493.914621,83.772868,913.043411,39.521628,20.156589,89.332558,6.009589,89.452713,1.044574,4397.190369,9.849104e+06,4.297984,4.373721,0.659861,12.324496
std,4.100731,7.737008,104.647959,30.072029,4.004891,913.288487,20.961719,3081.054405,19.588693,40.413556,11.668565,2.174595,11.520805,2.516636,6855.627214,2.392504e+07,3.672616,3.715745,0.140946,2.646186
min,2000.000000,45.300000,1.000000,0.000000,0.010000,0.099872,4.000000,0.000000,2.000000,0.000000,23.000000,0.740000,23.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.279000,4.200000
25%,2005.000000,65.900000,78.250000,0.000000,0.832500,41.531412,81.000000,0.000000,21.700000,1.000000,85.000000,4.560000,85.000000,0.100000,482.839936,2.007070e+05,1.600000,1.700000,0.572000,10.700000
50%,2008.000000,72.200000,146.000000,3.000000,3.965000,160.358620,93.000000,8.000000,46.000000,3.000000,94.000000,5.900000,94.000000,0.100000,1726.313819,1.365144e+06,2.800000,2.950000,0.690500,12.500000
75%,2012.000000,75.000000,217.750000,16.000000,7.380000,504.220204,96.000000,214.750000,56.100000,21.000000,97.000000,7.440000,97.000000,0.575000,4708.894890,7.227671e+06,6.600000,6.600000,0.755000,14.200000
max,2015.000000,89.000000,527.000000,372.000000,16.580000,5842.374765,99.000000,30509.000000,77.100000,461.000000,99.000000,12.600000,99.000000,19.000000,38852.361300,2.236146e+08,18.600000,18.800000,0.920000,20.500000

In [7]:
print(f"Total de linhas: {df.shape[0]}")
print(f"Total de colunas: {df.shape[1]}")

Total de linhas: 1290
Total de colunas: 22

In [8]:
df.dtypes

País                     object
Ano                       int64
Desenvolvimento          object
Expectativa_de_vida     float64
Mortalidade_adulta        int64
Mortes_infantis           int64
Álcool                  float64
Porcentagem_despesas    float64
Hepatite_B                int64
Sarampo                   int64
BMI                     float64
under-five_deaths         int64
Poliomielite              int64
Despesa_total           float64
Difteria                  int64
HIV/AIDS                float64
PIB                     float64
População               float64
Magreza_1_a_19_anos     float64
Magreza_5_a_9_anos      float64
Composição_de_renda     float64
Escolaridade            float64
dtype: object

In [9]:
print("Valores nulos por coluna:")
print(df.isnull().sum())

print("\nTotal de linhas duplicadas:", df.duplicated().sum())

Valores nulos por coluna:
País                    0
Ano                     0
Desenvolvimento         0
Expectativa_de_vida     0
Mortalidade_adulta      0
Mortes_infantis         0
Álcool                  0
Porcentagem_despesas    0
Hepatite_B              0
Sarampo                 0
BMI                     0
under-five_deaths       0
Poliomielite            0
Despesa_total           0
Difteria                0
HIV/AIDS                0
PIB                     0
População               0
Magreza_1_a_19_anos     0
Magreza_5_a_9_anos      0
Composição_de_renda     0
Escolaridade            0
dtype: int64

Total de linhas duplicadas: 0

### O que representa cada coluna:

- `País`: Nome do país.
- `Ano`: Ano da observação.
- `Desenvolvimento`: Categoria de desenvolvimento (Desenvolvido/Desenvolvimento).
- `Expectativa_de_vida`: Expectativa média de vida (anos).
- `Mortalidade_adulta`: Mortalidade entre adultos (por 1000 habitantes).
- `Mortes_infantis`: Número de mortes infantis.
- `Álcool`: Consumo médio de álcool per capita.
- `Porcentagem_despesas`: Porcentagem de despesas com saúde.
- `Hepatite_B`: Percentual de vacinação contra Hepatite B.
- `Sarampo`: Número de casos de sarampo.
- `BMI`: Índice de massa corporal médio.
- `under-five_deaths`: Mortes abaixo de 5 anos.
- `Poliomielite`: Cobertura de vacinação contra poliomielite.
- `Despesa_total`: Despesa total com saúde.
- `Difteria`: Cobertura de vacinação contra difteria.
- `HIV/AIDS`: Casos registrados de HIV/AIDS.
- `PIB`: Produto Interno Bruto per capita.
- `População`: População total.
- `Magreza_1_a_19_anos`: Porcentagem de magreza em jovens.
- `Magreza_5_a_9_anos`: Porcentagem de magreza em crianças.
- `Composição_de_renda`: Índice de distribuição de renda.
- `Escolaridade`: Média de anos de escolaridade.